# Generated by Django 3.1.4 on 2021-01-25 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210125_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 19, 52, 6, 611376, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
